version: '2'

services:
  crossblogs-app:
    image: stencil
    ports:
      - 8080:8080
    depends_on:
      - stencil-mysql

  crossblogs-mysql:
    extends:
        file: mysql.yml
        service: stencil-mysql